language: node_js

env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/garments

node_js:  
  - 12

before_script:
  - psql -c 'create database garments;' -U postgres
  - psql -U postgres -d garments -a -f ./sql/garment.sql

services:
  - postgresql